WIP: Update to mypy 0.900
https://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html
https://mypy.readthedocs.io/en/latest/config_file.html

The pydantic plugin is not yet compatible. See pydantic 2895.

The following error occurs:

```py
Error constructing plugin instance of PydanticPlugin

Traceback (most recent call last):
  File "/Users/brendon/dev/inboard/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/brendon/dev/inboard/.venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 98, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 229, in _build
  File "mypy/build.py", line 475, in load_plugins
  File "mypy/build.py", line 453, in load_plugins_from_config
  File "/Users/brendon/dev/inboard/.venv/lib/python3.9/site-packages/pydantic/mypy.py", line 77, in __init__
    self.plugin_config = PydanticPluginConfig(options)
  File "/Users/brendon/dev/inboard/.venv/lib/python3.9/site-packages/pydantic/mypy.py", line 114, in __init__
    plugin_config.read(options.config_file)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'pyproject.toml'
        [line 38]: ']\n'
```